// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnnotatedTrack = { 
/**
 * Bu bilgisayardaki yol (yeniden değerlendirme için; başka yere gönderilmez).
 */
path: string, fileName: string, title: string | null, artist: string | null, durationSecs: number | null, sizeBytes: number | null, };
