// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotatedTrack } from "./AnnotatedTrack";
import type { BeatEvaluation } from "./BeatEvaluation";

export type Annotation = { format: number, appVersion: string, savedAt: string, track: AnnotatedTrack, 
/**
 * İşaretlenen vuruşlar (saniye, artan).
 */
beats: Array<number>, 
/**
 * İşaretlenen droplar (saniye, artan).
 */
drops: Array<number>, 
/**
 * Son "doğruluğu ölç" sonucu.
 */
evaluation: BeatEvaluation | null, };
