// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Karşılama ekranında gösterilen program bilgisi.
 */
export type AppInfo = { name: string, version: string, phase: string, audioEngine: string, analysis: string, visualBridge: string, 
/**
 * "Dosya aç" penceresinde gösterilecek uzantılar.
 */
supportedExtensions: Array<string>, };
