// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Atmosphere = { 
/**
 * Bölümün sırası.
 */
section: number, 
/**
 * Bölümün etiketi: benzer bölümler (ör. her nakarat) aynı temayı alır.
 */
theme: number, 
/**
 * Ruh hâli: 0 sakin … 1 yoğun (bölüm enerjisi, bölüm geçişlerinde yumuşak).
 */
mood: number, 
/**
 * Sıcaklık: 0 soğuk … 1 sıcak.
 */
warmth: number, };
