// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bir şarkının beat değerlendirmesi.
 */
export type BeatEvaluation = { 
/**
 * İşaretlere doğrudan göre F-ölçüsü (0..1).
 */
fMeasure: number, 
/**
 * İşaretlerin bulunan vuruşlara göre ortanca kayması (ms; artı: işaret geç).
 */
tapOffsetMs: number, 
/**
 * Bu kayma düzeltildikten sonraki F-ölçüsü.
 */
fMeasureAligned: number, detectedBpm: number | null, 
/**
 * İşaretlerden çıkan tempo (ardışık vuruş aralıklarının ortancası).
 */
markedBpm: number | null, detectedCount: number, markedCount: number, 
/**
 * Programın bulduğu droplar (saniye).
 */
detectedDrops: Array<number>, 
/**
 * İşaretlenen droplardan, programın ±`DROP_TOLERANCE` içinde bulduğu.
 */
dropHits: number, markedDrops: number, };
