// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * O anın vuruş ızgarasındaki yeri.
 */
export type BeatFrame = { 
/**
 * Şarkının temposu (vuruş/dakika).
 */
bpm: number, 
/**
 * Son vuruşun sırası (0'dan başlar).
 */
index: number, 
/**
 * Son vuruştan bu yana geçen süre, vuruş aralığına oranla (0..1).
 */
phase: number, 
/**
 * Vuruşun ölçüdeki yeri (1 = ölçü başı); yapı analizi bitene kadar `null`.
 */
barBeat: number | null, 
/**
 * Ölçüdeki vuruş sayısı (3 ya da 4); yapı analizi bitene kadar `null`.
 */
meter: number | null, };
