// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Senkron ölçümü için tıklama kaydı: dosya yolu ve tıklamaların zamanları.
 */
export type CalibrationTrack = { path: string, clicks: Array<number>, };
