// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Atmosphere } from "./Atmosphere";
import type { Rhythm } from "./Rhythm";
import type { Texture } from "./Texture";

/**
 * Bir anın yönetmen notu.
 */
export type DirectorFrame = { atmosphere: Atmosphere, rhythm: Rhythm, texture: Texture, };
