// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pencereye bırakılanların sonucu.
 */
export type DropOutcome = { 
/**
 * Çalınacak şarkılar, bırakılış sırasıyla (zaten kütüphanede olanlar dahil).
 */
tracks: Array<string>, 
/**
 * Kütüphaneye yeni eklenen şarkılar.
 */
addedTracks: number, 
/**
 * Kütüphaneye yeni eklenen klasörler (şarkıları arka planda taranır).
 */
addedFolders: number, 
/**
 * Zaten kütüphanede olanlar (şarkı ya da klasör).
 */
already: number, 
/**
 * Eklenemeyenler (ör. "Bu dosya türü desteklenmiyor: notlar.txt").
 */
problems: Array<string>, };
