// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kullanıcının ekolayzer ayarları. Ayarlar dosyasında da bu biçimde saklanır.
 */
export type EqSettings = { enabled: boolean, gainsDb: Array<number>, 
/**
 * Bas düğmesi (0–18 dB, 100 Hz raf; 12 dB üstü kulüp bölgesi; bkz. [`super::bass`]).
 */
bassDb: number, 
/**
 * Küçük hoparlör bası: alt bas yerine harmonikleri (dizüstü ve küçük hoparlörler).
 */
smallSpeaker: boolean, 
/**
 * Derinlik (0–1): bas notalarının bir oktav altı eklenir.
 */
bassDepth: number, 
/**
 * Vuruş (0–1): davul vuruşlarının ilk anı güçlenir (bkz. [`super::punch`]).
 */
bassPunch: number, };
