// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kullanıcının ekolayzer ayarları. Ayarlar dosyasında da bu biçimde saklanır.
 */
export type EqSettings = { enabled: boolean, gainsDb: Array<number>, 
/**
 * Bas düğmesi (0–12 dB, 100 Hz raf; bkz. [`super::bass`]).
 */
bassDb: number, 
/**
 * Küçük hoparlör bası: alt bas yerine harmonikleri (dizüstü ve küçük hoparlörler).
 */
smallSpeaker: boolean, };
