// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kullanıcının ekolayzer ayarları. Ayarlar dosyasında da bu biçimde saklanır.
 */
export type EqSettings = { enabled: boolean, gainsDb: Array<number>, };
