// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arayüzün gösterdiği ekolayzer durumu: ayarlar ve gerçekten uygulanan eğri.
 */
export type EqState = { enabled: boolean, gainsDb: Array<number>, bandsHz: Array<number>, maxGainDb: number, 
/**
 * Kırpılmayı önlemek için düşürülen kazanç (dB, ≤ 0).
 */
preampDb: number, 
/**
 * Filtrelerin toplam tepkisi (ön kazanç hariç): frekanslar (Hz) ve kazançlar (dB).
 */
curveHz: Array<number>, curveDb: Array<number>, };
