// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arayüzün gösterdiği ekolayzer durumu: ayarlar ve gerçekten uygulanan eğri.
 */
export type EqState = { enabled: boolean, gainsDb: Array<number>, bassDb: number, smallSpeaker: boolean, maxBassDb: number, bandsHz: Array<number>, maxGainDb: number, 
/**
 * Taşmayı önlemek için düşürülen kazanç (dB, ≤ 0): çalan şarkının boşluğunun
 * yetmediği kadar.
 */
preampDb: number, 
/**
 * Filtrelerin (bas düğmesi dahil) toplam tepkisi, ön kazanç hariç: frekanslar (Hz)
 * ve kazançlar (dB).
 */
curveHz: Array<number>, curveDb: Array<number>, };
