// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterKind } from "./FilterKind";

export type HeadphoneFilter = { kind: FilterKind, freqHz: number, gainDb: number, q: number, };
