// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadphoneProfile } from "./HeadphoneProfile";

/**
 * Arayüze giden durum: ayar ve çizim için düzeltme eğrisi.
 */
export type HeadphoneState = { enabled: boolean, profile: HeadphoneProfile | null, 
/**
 * Eğrinin frekansları (Hz) ve kazançları (dB, ön kazanç dahil); profil yoksa boş.
 */
curveHz: Array<number>, curveDb: Array<number>, };
