// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeadphoneFilter } from "./HeadphoneFilter";

/**
 * Bir kulaklığın düzeltme profili.
 */
export type HeadphoneProfile = { 
/**
 * Kullanıcıya gösterilen ad (genellikle kulaklık modeli).
 */
name: string, 
/**
 * Bozulmayı önleyen ön kazanç (dB, ≤ 0).
 */
preampDb: number, filters: Array<HeadphoneFilter>, };
