// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kütüphanedeki bir klasör.
 */
export type LibraryFolder = { id: number, path: string, };
