// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Listede gösterilen bir şarkı.
 */
export type LibraryTrack = { id: number, path: string, 
/**
 * Etiketteki başlık, yoksa dosya adı.
 */
title: string, artist: string | null, album: string | null, trackNumber: number | null, durationSecs: number | null, codec: string, 
/**
 * Tempo (önbellekteki geçerli analizden); analiz edilmediyse ya da ritim yoksa `None`.
 */
bpm: number | null, 
/**
 * Geçerli bir analizi var mı (ritimsiz şarkılar da analiz edilmiş sayılır).
 */
analyzed: boolean, };
