// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryFolder } from "./LibraryFolder";
import type { ScanProgress } from "./ScanProgress";

/**
 * Arayüzün gösterdiği kütüphane durumu.
 */
export type LibraryStatus = { folders: Array<LibraryFolder>, trackCount: number, 
/**
 * Analizi hazır şarkı sayısı (BPM ve şarkı haritası önbellekte).
 */
analyzed: number, scan: ScanProgress, 
/**
 * Son taramadaki sorunlar (ör. "Klasör bulunamadı: D:\Müzik").
 */
problems: Array<string>, };
