// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Çalma seçenekleri (kalıcı ayar). Yeni alanlar eklendiğinde eski ayar dosyaları
 * varsayılanla tamamlanır.
 */
export type PlaybackOptions = { 
/**
 * Ses yüksekliği eşitlemesi (EBU R128): bütün şarkılar aynı yükseklikte çalar,
 * ekolayzere yer açılır. Proje sahibinin kararıyla varsayılan açık.
 */
normalize: boolean, 
/**
 * Bit-perfect: aygıt özel modda, şarkının kendi hızında açılır; ses hiç işlenmez
 * (ekolayzer, kulaklık düzeltmesi, eşitleme devre dışı). Proje sahibinin kararıyla
 * varsayılan kapalı.
 */
bitPerfect: boolean, };
