// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybackState } from "./PlaybackState";
import type { SignalPath } from "./SignalPath";
import type { TrackInfo } from "./TrackInfo";

/**
 * Arayüzün düzenli aralıklarla sorguladığı durum özeti.
 */
export type PlaybackStatus = { state: PlaybackState, track: TrackInfo | null, positionSecs: number, underruns: number, error: string | null, 
/**
 * Şarkının temposu (BPM); analiz bitene kadar ya da belirgin ritim yoksa `None`.
 */
bpm: number | null, 
/**
 * Sesin aygıta giden yolu; şarkı açık değilse `None`.
 */
output: SignalPath | null, };
