// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Oynatıcının durumu.
 */
export type PlaybackState = "idle" | "playing" | "paused" | "ended" | "error";
