// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Rhythm = { 
/**
 * Vuruş nabzı: vuruşta 1'e çıkar, sonra söner (0..1).
 */
pulse: number, 
/**
 * Ölçü başı vurgusu (0..1).
 */
accent: number, 
/**
 * Vuruşun içindeki yer (0..1) ve ölçünün içindeki yer (0..1).
 */
beatPhase: number, barPhase: number, 
/**
 * Droptan önceki gerilim: 0 → 1 (drop anında 1).
 */
anticipation: number, 
/**
 * Drop anındaki açılım: 1 → 0.
 */
release: number, };
