// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tarama durumunun anlık görüntüsü.
 */
export type ScanProgress = { scanning: boolean, 
/**
 * Taranan klasördeki ses dosyası sayısı.
 */
found: number, 
/**
 * İşlenen dosya sayısı (değişmeyenler dahil).
 */
processed: number, 
/**
 * Şu an taranan klasör.
 */
current: string | null, };
