// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Section = { start: number, end: number, 
/**
 * Bölümün ortalama enerjisi (0..1).
 */
energy: number, 
/**
 * Benzer bölümler aynı etiketi alır (ör. her nakarat): 0, 1, 2… ilk görülme sırasıyla.
 */
label: number, };
