// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sesin şarkıdan hoparlöre giden yolu (profesyonel çalarlardaki "sinyal yolu").
 */
export type SignalPath = { 
/**
 * Aygıtın adı (ör. "Hoparlörler (Realtek(R) Audio)"); bilinmiyorsa boş.
 */
deviceName: string, 
/**
 * Aygıta giden örnekleme hızı ve kanal sayısı.
 */
sampleRate: number, channels: number, 
/**
 * Şarkı aygıtın hızına Lyraska'nın yüksek kaliteli dönüştürücüsüyle çevriliyor mu?
 */
resampled: boolean, };
