// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Section } from "./Section";

/**
 * Şarkının yapısı.
 */
export type SongMap = { 
/**
 * Ölçüdeki vuruş sayısı (3 ya da 4).
 */
meter: number, 
/**
 * İlk tam ölçünün başladığı vuruşun sırası (0..meter).
 */
downbeatPhase: number, 
/**
 * Ölçü başlarının zamanları (saniye).
 */
downbeats: Array<number>, sections: Array<Section>, 
/**
 * Drop anları (saniye).
 */
drops: Array<number>, 
/**
 * Saniyede bir enerji değeri (0..1).
 */
energy: Array<number>, };
