// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Texture = { 
/**
 * Ayrıntı: tizlerin canlılığı (0..1, şarkıya göre).
 */
detail: number, 
/**
 * Hareket: vuruş yoğunluğu (0..1, şarkıya göre).
 */
motion: number, };
