// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Açılan şarkının bilgileri.
 */
export type TrackInfo = { path: string, 
/**
 * Dosya adı (uzantısız); etiket yoksa başlık olarak kullanılır.
 */
fileName: string, title: string | null, artist: string | null, album: string | null, albumArtist: string | null, trackNumber: number | null, discNumber: number | null, 
/**
 * Kodek adı (ör. "flac", "mp3").
 */
codec: string, sampleRate: number, channels: number, 
/**
 * Süre (saniye); dosya bildirmiyorsa `None`.
 */
durationSecs: number | null, };
