// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeatFrame } from "./BeatFrame";
import type { DirectorFrame } from "./DirectorFrame";

/**
 * Arayüzün her ekran karesinde istediği görsel veri.
 */
export type VisualFrame = { 
/**
 * Verinin ait olduğu çalma konumu (saniye).
 */
positionSecs: number, 
/**
 * Logaritmik aralıklı frekans bantları (bastan tize), 0..1.
 */
bands: Array<number>, 
/**
 * Sol/sağ etkin (RMS) seviye, dBFS. Sessizlik −60.
 */
rmsDb: [number, number], 
/**
 * Sol/sağ tepe seviye, dBFS. Sessizlik −60.
 */
peakDb: [number, number], 
/**
 * 0 VU'ya denk gelen seviye (dBFS): şarkının yüksek bölümlerine göre.
 * Analiz bitene kadar `null`.
 */
vuReferenceDb: number | null, 
/**
 * Tempo ve vuruş konumu; analiz bitene kadar ya da ritim yoksa `null`.
 */
beat: BeatFrame | null, 
/**
 * Şarkının o anki enerjisi (0..1, şarkıya göre); analiz bitene kadar `null`.
 */
energy: number | null, 
/**
 * O anki bölümün sırası; analiz bitene kadar `null`.
 */
section: number | null, 
/**
 * Görsel Yönetmen'in o anki notu (atmosfer, ritim, doku); analiz bitene kadar `null`.
 */
director: DirectorFrame | null, };
